spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chocoshop?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: amlayes
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    mode: HTML

  mvc:
    static-path-pattern: /**

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/home/yvo11/upload/

server:
  port: 4430
  ssl:
    key-store: classpath:keystore
    key-store-password: 123456
    keyStoreType: JKS
    keyAlias: tomcat

memcache:
  server: 127.0.0.1:11211
  poolSize: 20
  sanitizeKeys: false
  opTimeout: 3000