spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chocoshop?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    cache: false
    mode: LEGACYHTML5

  mvc:
    static-path-pattern: /**

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:C:\upload\

server:
  port: 443
  ssl:
    key-store: classpath:keystore
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: tomcat

memcache:
  server: 127.0.0.1:11211
  poolSize: 20
  sanitizeKeys: false
  opTimeout: 3000